Warps:
    #Time in seconds by default
    TimeToTeleport: 5
    #Time in seconds per group
    TimePerGroup: 
        - algo: 20
        - otro: 50
        - test: 3
Spawnpoint:
    #Set none to disable it. Use /setspawn in-game to configure it
    default: none
    SpawnPerGroup:
        - algo: none
        - otro: none
        - test: none
        
    