Warps:
    #Time in seconds by default
    TimeToTeleport: 5
    #Time in seconds per group
    TimePerGroup: 
        - some: 20
        - group: 50
        - test: 3
Spawnpoint:
    #Set none to disable it. Use /setspawn in-game to configure it
    #It's not necessary set each group, only what you need
    default: none
    SpawnPerGroup:
        - some: none
        - group: none
        - test: none
        
    